import ChainIds from './chain-ids'
import Chains from './chains'
import * as ethers from 'ethers'
import Web3 from 'web3'
import PublicRpcEndpoints from './public-rpc-endpoints'

export const ETHERS_PROVIDERS: { [chainId: number]: any } = {
  [ChainIds.MAINNET]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MAINNET),
  [ChainIds.SMART_CHAIN]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.SMART_CHAIN),
  [ChainIds.MATIC]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.POLYGON),
  [ChainIds.AVALANCHE]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.AVALANCHE_CCHAIN),
  [ChainIds.FANTOM]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.FANTOM),
  [ChainIds.METIS_NETWORK]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.METIS_ANDROMEDA),
  [ChainIds.ARBITRUM]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.ARBITRUM),
  [ChainIds.AURORA]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.AURORA),
  [ChainIds.RINKEBY]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.RINKEBY),
  [ChainIds.GOERLI]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.GOERLI),
  [ChainIds.GNOSIS]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.GNOSIS),
  [ChainIds.OPTIMISM]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.OPTIMISM),
  [ChainIds.KOVAN]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.KOVAN),
  [ChainIds.FUJI]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.FUJI),
  [ChainIds.NEWMONEY_CHAIN]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.NEWMONEY_CHAIN),
  [ChainIds.SMART_CHAIN_TEST]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.SMART_CHAIN_TEST),
  [ChainIds.MOONBASE_ALPHA]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MOONBASE_ALPHA),
  [ChainIds.MOONRIVER]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MOONRIVER),
  [ChainIds.MUMBAI]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MUMBAI),
  [ChainIds.MODE]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MODE),
  [ChainIds.HECO]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.HECO),
  [ChainIds.BASE]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.BASE),
  [ChainIds.MANTLE]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MANTLE),
  [ChainIds.SHIDEN]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.SHIDEN),
  [ChainIds.IOTEX]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.IOTEX),
  [ChainIds.HARMONY]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.HARMONY),
  [ChainIds.CRONOS]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.CRONOS),
  [ChainIds.OKEX]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.OKEX),
  [ChainIds.MULTIVAC]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MULTIVAC),
  [ChainIds.MOONBEAM]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.MOONBEAM),
  [ChainIds.METIS_STARDUST]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.METIS_STARDUST),
  [ChainIds.ARBITRUM_TEST]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.ARBITRUM_TEST),
  [ChainIds.KLAYTN]: new ethers.providers.JsonRpcProvider(PublicRpcEndpoints.KLAYTN),
}

export const WEB3_PROVIDERS: { [chainId: number]: any } = {
  [ChainIds.MAINNET]: new Web3(PublicRpcEndpoints.ETH_MAINNET),
  [ChainIds.SMART_CHAIN]: new Web3(PublicRpcEndpoints.SMART_CHAIN),
  [ChainIds.MATIC]: new Web3(PublicRpcEndpoints.POLYGON),
  [ChainIds.AVALANCHE]: new Web3(PublicRpcEndpoints.AVALANCHE_CCHAIN),
  [ChainIds.FANTOM]: new Web3(PublicRpcEndpoints.FANTOM),
  [ChainIds.METIS_NETWORK]: new Web3(PublicRpcEndpoints.METIS_ANDROMEDA),
  [ChainIds.ARBITRUM]: new Web3(PublicRpcEndpoints.ARBITRUM),
  [ChainIds.AURORA]: new Web3(PublicRpcEndpoints.AURORA),
  [ChainIds.RINKEBY]: new Web3(PublicRpcEndpoints.RINKEBY),
  [ChainIds.GOERLI]: new Web3(PublicRpcEndpoints.GOERLI),
  [ChainIds.GNOSIS]: new Web3(PublicRpcEndpoints.GNOSIS),
  [ChainIds.OPTIMISM]: new Web3(PublicRpcEndpoints.OPTIMISM),
  [ChainIds.KOVAN]: new Web3(PublicRpcEndpoints.KOVAN),
  [ChainIds.FUJI]: new Web3(PublicRpcEndpoints.FUJI),
  [ChainIds.NEWMONEY_CHAIN]: new Web3(PublicRpcEndpoints.NEWMONEY_CHAIN),
  [ChainIds.SMART_CHAIN_TEST]: new Web3(PublicRpcEndpoints.SMART_CHAIN_TEST),
  [ChainIds.MOONBASE_ALPHA]: new Web3(PublicRpcEndpoints.MOONBASE_ALPHA),
  [ChainIds.MOONRIVER]: new Web3(PublicRpcEndpoints.MOONRIVER),
  [ChainIds.MUMBAI]: new Web3(PublicRpcEndpoints.MUMBAI),
  [ChainIds.MODE]: new Web3(PublicRpcEndpoints.MODE),
  [ChainIds.HECO]: new Web3(PublicRpcEndpoints.HECO),
  [ChainIds.BASE]: new Web3(PublicRpcEndpoints.BASE),
  [ChainIds.MANTLE]: new Web3(PublicRpcEndpoints.MANTLE),
  [ChainIds.SHIDEN]: new Web3(PublicRpcEndpoints.SHIDEN),
  [ChainIds.IOTEX]: new Web3(PublicRpcEndpoints.IOTEX),
  [ChainIds.HARMONY]: new Web3(PublicRpcEndpoints.HARMONY),
  [ChainIds.CRONOS]: new Web3(PublicRpcEndpoints.CRONOS),
  [ChainIds.OKEX]: new Web3(PublicRpcEndpoints.OKEX),
  [ChainIds.MULTIVAC]: new Web3(PublicRpcEndpoints.MULTIVAC),
  [ChainIds.MOONBEAM]: new Web3(PublicRpcEndpoints.MOONBEAM),
  [ChainIds.METIS_STARDUST]: new Web3(PublicRpcEndpoints.METIS_STARDUST),
  [ChainIds.ARBITRUM_TEST]: new Web3(PublicRpcEndpoints.ARBITRUM_TEST),
  [ChainIds.KLAYTN]: new Web3(PublicRpcEndpoints.KLAYTN),
}
