import ChainIds from './chain-ids';

const PublicRpcEndpoints: any = {
  [ChainIds.AURORA]: 'https://aurora.drpc.org',
  [ChainIds.MAINNET]: 'https://rpc.ankr.com/eth',
  [ChainIds.RINKEBY]: 'https://rinkeby.infura.io/3/9aa3d95b3bc440fa88ea12eaa4456161',
  [ChainIds.GOERLI]: 'https://ethereum-goerli-rpc.publicnode.com',
  [ChainIds.GNOSIS]: 'https://gnosis-rpc.publicnode.com',
  [ChainIds.OPTIMISM]: 'https://optimism-rpc.publicnode.com',
  [ChainIds.KOVAN]: 'https://kovan.poa.network',
  [ChainIds.FUJI]: 'https://avalanche-fuji.drpc.org',
  [ChainIds.NEWMONEY_CHAIN]: 'https://cashchain-rpc.newmoney.ai',
  [ChainIds.SMART_CHAIN]: 'https://bsc-dataseed.binance.org',
  [ChainIds.SMART_CHAIN_TEST]: 'https://bsc-testnet.drpc.org',
  [ChainIds.MOONBASE_ALPHA]: 'https://moonbase-alpha.drpc.org',
  [ChainIds.MOONRIVER]: 'https://moonriver.drpc.org',
  [ChainIds.MUMBAI]: 'https://polygon-mumbai-bor-rpc.publicnode.com',
  [ChainIds.MATIC]: 'https://polygon-rpc.com',
  [ChainIds.MODE]: 'https://mainnet.mode.network',
  [ChainIds.HECO]: 'https://http-mainnet-node.huobichain.com',
  [ChainIds.ARBITRUM]: 'https://arb1.arbitrum.io/rpc',
  [ChainIds.AVALANCHE]: 'https://api.avax.network/ext/bc/C/rpc',
  [ChainIds.BASE]: 'https://mainnet.base.org',
  [ChainIds.MANTLE]: 'https://rpc.mantle.xyz',
  [ChainIds.SOLANA]: 'https://solana-mainnet.g.alchemy.com/v2/demo',
  [ChainIds.SUI]: 'https://fullnode.mainnet.sui.io',
  [ChainIds.BITCOIN]: 'https://api.blockcypher.com/v1/btc/main',
  [ChainIds.FANTOM]: 'https://fantom-pokt.nodies.app',
  [ChainIds.SHIDEN]: 'https://shiden.api.onfinality.io/public',
  [ChainIds.IOTEX]: 'https://iotex-network.rpc.thirdweb.com',
  [ChainIds.HARMONY]: 'https://hmyone-pokt.nodies.app',
  [ChainIds.CRONOS]: 'https://cronos-evm-rpc.publicnode.com',
  [ChainIds.OKEX]: 'https://oktc.drpc.org',
  [ChainIds.MULTIVAC]: 'https://rpc.mtv.ac',
  [ChainIds.METIS_NETWORK]: 'https://metis.drpc.org',
  [ChainIds.MOONBEAM]: 'https://moonbeam.drpc.org',
  [ChainIds.METIS_STARDUST]: 'https://stardust.metis.io/?owner=588',
  [ChainIds.ARBITRUM_TEST]: 'https://rinkeby.arbitrum.io/rpc',
  [ChainIds.KLAYTN]: 'https://kaia.blockpi.network/v1/rpc/public',
  [ChainIds.SOLANA_LIFI]: 'https://solana-mainnet.g.alchemy.com/v2/demo',
  [ChainIds.SOLANA_LEGACY]: 'https://solana-mainnet.g.alchemy.com/v2/demo',
  [ChainIds.BITCOIN_LIFI]: 'https://api.blockcypher.com/v1/btc/main',
} as const;

export default PublicRpcEndpoints;
